codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

# Local .coveragerc file handles exclusions for local testing
# This configuration is for the Codecov service and CI integration

ignore:
  - "**/migrations/"  # Exclude Django migrations
  - "**/tests/"      # Exclude test files
  - "**/admin.py"    # Exclude Django admin files
  - "**/config/"     # Exclude configuration files
  - "**/manage.py"   # Exclude Django management script
